server_names = ['odohtarget']
listen_addresses = ['127.0.0.1:5300']

[query_log]
file = 'query.log'

[static]
  [static.'odohtarget']
  stamp = 'sdns://BQcAAAAAAAAADm9kb2guY3J5cHRvLnN4Ci9kbnMtcXVlcnk'

  [static.'odohrelay']
  stamp = 'sdns://hQcAAAAAAAAADDg5LjM4LjEzMS4zOAAYb2RvaC1ubC5hbGVrYmVyZy5uZXQ6NDQzBi9wcm94eQ'

[anonymized_dns]
  routes = [
    { server_name='odohtarget', via=['odohrelay'] }
  ]
